apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: open-telemetry
  pass_credentials_all: false
  password: ""
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bedag
  pass_credentials_all: false
  password: ""
  url: https://s3.mgmtbi.ch/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bedag-unstable
  pass_credentials_all: false
  password: ""
  url: https://s3.mgmtbi.ch/helm-charts/unstable
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: camunda
  pass_credentials_all: false
  password: ""
  url: https://helm.cch.camunda.cloud
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: clastix
  pass_credentials_all: false
  password: ""
  url: https://clastix.github.io/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: grafana
  pass_credentials_all: false
  password: ""
  url: https://grafana.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: argo
  pass_credentials_all: false
  password: ""
  url: https://argoproj.github.io/argo-helm
  username: ""

