# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000
continuation_prompt = '... '

[character]
disabled = false

[cmd_duration]
min_time_to_notify = 300_000
show_notifications = true
disabled = false

[container]
disabled = false

[directory]
format = "at [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
truncation_symbol = "…/"
read_only = " ro"
disabled = false

[env_var.KXLOCK]
format = 'with [locked context]($style) '

[git_branch]
symbol = "git "
disabled = false

[git_commit]
tag_symbol = " tag "
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
disabled = false

[golang]
symbol = "go "
disabled = false

[kubernetes]
format = 'via [$symbol $context\($namespace\)]($style) '
symbol = "⛵"
style = "bold red"
disabled = false

[[kubernetes.contexts]]
context_pattern = ".*dev.*|.*kind.*"
style = "bold green"

[[kubernetes.contexts]]
context_pattern = ".*test.*|.*stage.*"
style = "bold yellow"

[line_break]
disabled = false

[sudo]
symbol = "sudo "
disabled = false

[aws]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[gleam]
disabled = true

[guix_shell]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[localip]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[hg_branch]
disabled = true

[nats]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[odin]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[quarto]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[typst]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
